# Generated by Django 6.0 on 2026-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolamiento',
            fields=[
                ('id_enrolamiento', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(max_length=18)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('materno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('adscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_vig', models.DateField(blank=True, null=True)),
                ('fin_vig', models.DateField(blank=True, null=True)),
                ('eladia', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('impreso', models.IntegerField(blank=True, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('provisional', models.IntegerField(blank=True, db_column='provisional', null=True)),
                ('id_usuario_registra', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_enrolamiento', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_carga', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('nuevo_laredo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes de Enrolamiento',
                'db_table': 'sicre_tbl_enrolamiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnrolamientoFamiliar',
            fields=[
                ('id_enrolamiento', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(max_length=18)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('materno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('adscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_vig', models.DateField(blank=True, null=True)),
                ('fin_vig', models.DateField(blank=True, null=True)),
                ('eladia', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_familiares', models.CharField(blank=True, max_length=50, null=True)),
                ('impreso', models.IntegerField(blank=True, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('provisional', models.IntegerField(blank=True, db_column='provisional', null=True)),
                ('id_usuario_registra', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_enrolamiento', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('ultima_carga', models.DateTimeField(auto_now=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('nuevo_laredo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expediente Familiar',
                'verbose_name_plural': 'Expedientes de Enrolamiento Familiar',
                'db_table': 'sicre_tbl_enrolamiento_familiar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SicreTblSig',
            fields=[
                ('num_empleado', models.CharField(blank=True, max_length=20, null=True)),
                ('rfc', models.CharField(blank=True, max_length=18, null=True)),
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('materno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('adscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_vig', models.DateField(blank=True, null=True)),
                ('fin_vig', models.DateField(blank=True, null=True)),
                ('eladia', models.CharField(blank=True, max_length=20, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_carga', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SICRE-sig',
                'verbose_name_plural': 'SICRE-SIG',
                'db_table': 'sicre_tbl_sig',
                'managed': True,
            },
        ),
    ]
