# Generated by Django 5.1.15 on 2026-02-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicretblsig',
            name='firma',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
