# Generated by Django 5.1.15 on 2026-01-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargaMasiva',
        ),
        migrations.AlterModelOptions(
            name='sicretblsig',
            options={'managed': True, 'verbose_name': 'SICRE-sig', 'verbose_name_plural': 'SICRE-SIG'},
        ),
        migrations.AddField(
            model_name='enrolamiento',
            name='impreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='enrolamiento',
            table='sicre_tbl_enrolamiento',
        ),
    ]
