# Generated by Django 6.0 on 2026-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0002_sicretblsig_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolamiento',
            name='rfc',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='sicretblsig',
            name='rfc',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
