# Generated by Django 5.2.3 on 2026-03-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0003_enrolamiento_layout_credencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolamientofamiliar',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrolamientofamiliar',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrolamientofamiliar',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrolamientofamiliar',
            name='placas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrolamientofamiliar',
            name='vivienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
