# Generated by Django 6.0 on 2026-03-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0004_enrolamientofamiliar_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolamientofamiliar',
            name='nombre_reverso',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
