# Generated by Django 6.0 on 2026-03-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0005_enrolamientofamiliar_nombre_reverso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaMasiva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=18)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('foto', models.BinaryField(blank=True, null=True)),
                ('firma', models.BinaryField(blank=True, null=True)),
                ('lote', models.CharField(max_length=100)),
                ('fecha_enrolamiento', models.DateTimeField(auto_now_add=True)),
                ('usuario_enrola', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sicre_tbl_carga_masiva',
            },
        ),
    ]
