# Generated by Django 6.0 on 2026-03-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0006_cargamasiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargamasiva',
            name='adscripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='eladia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='fin_vig',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='id_usuario_modifica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='id_usuario_registra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='impreso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='inicio_vig',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='layout_credencial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='nivel_credencial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='nuevo_laredo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='num_empleado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='paterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='provisional',
            field=models.IntegerField(blank=True, db_column='provisional', null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='ultima_carga',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
