# Generated by Django 6.0 on 2026-03-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0007_cargamasiva_adscripcion_cargamasiva_apellidos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargamasiva',
            old_name='adscripcion',
            new_name='estado_hum',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='eladia',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='materno',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='num_empleado',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='paterno',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='puesto',
        ),
        migrations.RemoveField(
            model_name='cargamasiva',
            name='ultima_carga',
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='area',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='cargo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='cargo_drh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='empleado_anam',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='estado_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='estatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='firma_drh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='no_empleado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='nombres',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='qr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargamasiva',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
