# Generated by Django 5.1.15 on 2026-08-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0008_rename_adscripcion_cargamasiva_estado_hum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolamientoCredencial',
            fields=[
                ('id_enrolamiento', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('rfc', models.CharField(max_length=18)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('materno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('puesto', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('adscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('inicio_vig', models.DateField(blank=True, null=True)),
                ('fin_vig', models.DateField(blank=True, null=True)),
                ('foto', models.CharField(blank=True, max_length=255, null=True)),
                ('firma', models.CharField(blank=True, max_length=255, null=True)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('provisional', models.IntegerField(blank=True, db_column='provisional', null=True)),
                ('impreso', models.IntegerField(blank=True, null=True)),
                ('layout_credencial', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_usuario_registra', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Enrolamiento (credencial)',
                'verbose_name_plural': 'Enrolamientos (credencial)',
                'db_table': 'sicre_tbl_enrolamiento_credencial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlantillaCredencial',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fondo_frente', models.CharField(blank=True, max_length=255, null=True)),
                ('fondo_reverso', models.CharField(blank=True, max_length=255, null=True)),
                ('canvas_frente', models.JSONField(blank=True, null=True)),
                ('canvas_reverso', models.JSONField(blank=True, null=True)),
                ('ancho_px', models.IntegerField(default=638)),
                ('alto_px', models.IntegerField(default=1016)),
                ('ancho_mm', models.DecimalField(decimal_places=2, default=54, max_digits=6)),
                ('alto_mm', models.DecimalField(decimal_places=2, default=86, max_digits=6)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_usuario_registra', models.IntegerField(blank=True, null=True)),
                ('id_usuario_modifica', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plantilla de credencial',
                'verbose_name_plural': 'Plantillas de credencial',
                'db_table': 'sicre_tbl_plantilla_credencial',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
    ]
