# Generated by Django 5.1.15 on 2026-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0009_enrolamientocredencial_plantillacredencial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='adscripcion',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='area',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='foto',
        ),
        # RenameField (no Remove+Add) para preservar los valores ya guardados
        # en los registros existentes -- layout_credencial pasa a llamarse
        # plantilla_credencial sin perder datos.
        migrations.RenameField(
            model_name='enrolamientocredencial',
            old_name='layout_credencial',
            new_name='plantilla_credencial',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='materno',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='paterno',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='puesto',
        ),
        migrations.AlterField(
            model_name='enrolamientocredencial',
            name='plantilla_credencial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
