# Generated by Django 5.1.15 on 2026-08-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0010_remove_enrolamientocredencial_adscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacredencial',
            name='por_defecto',
            field=models.BooleanField(default=False),
        ),
    ]
