# Generated by Django 5.1.15 on 2026-08-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0011_plantillacredencial_por_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicretblsig',
            name='fecha_primera_deteccion',
            field=models.DateTimeField(blank=True, db_column='FECHA_PRIMERA_DETECCION', null=True),
        ),
    ]
