# Generated by Django 5.1.15 on 2026-08-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0012_sicretblsig_fecha_primera_deteccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivoFolio',
            fields=[
                ('id_consecutivo', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(default='credencial', max_length=50, unique=True)),
                ('valor', models.IntegerField(default=1)),
                ('longitud', models.IntegerField(default=6)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_usuario_modifica', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sicre_tbl_consecutivo_folio',
                'managed': True,
            },
        ),
    ]
