# Generated by Django 5.1.15 on 2026-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0013_consecutivofolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadAdministrativa',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_normalizado', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nombre_compactado', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sicre_tbl_unidad_administrativa',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
    ]
