# Generated by Django 5.1.15 on 2026-08-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0014_unidadadministrativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadadministrativa',
            name='es_direccion_general',
            field=models.BooleanField(default=False),
        ),
    ]
