# Generated by Django 5.1.15 on 2026-08-06 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0015_unidadadministrativa_es_direccion_general'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadadministrativa',
            name='es_direccion_general',
        ),
    ]
