# Generated by Django 5.1.15 on 2026-08-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0016_remove_unidadadministrativa_es_direccion_general'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unidadadministrativa',
            table='sicre_cat_unidad_compactada',
        ),
    ]
