# Generated by Django 5.1.15 on 2026-08-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0017_alter_unidadadministrativa_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolamientocredencial',
            options={'managed': True, 'ordering': ['-fecha_registro'], 'verbose_name': 'Enrolamiento (credencial)', 'verbose_name_plural': 'Enrolamientos (credencial)'},
        ),
        migrations.AddField(
            model_name='enrolamientocredencial',
            name='canvas_frente',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrolamientocredencial',
            name='canvas_reverso',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
