# Generated by Django 5.1.15 on 2026-08-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0018_alter_enrolamientocredencial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='impreso',
        ),
    ]
