# Generated by Django 5.1.15 on 2026-08-06 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0019_remove_enrolamientocredencial_impreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='inicio_vig',
        ),
        migrations.RemoveField(
            model_name='enrolamientocredencial',
            name='rfc',
        ),
    ]
