# Generated by Django 5.1.15 on 2026-08-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0020_remove_enrolamientocredencial_inicio_vig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolamientocredencial',
            name='con_ajustes',
            field=models.BooleanField(default=False),
        ),
    ]
