# Generated by Django 5.1.15 on 2026-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0022_backfill_con_ajustes'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolamientocredencial',
            name='medios',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
