# Generated by Django 5.1.15 on 2026-08-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0023_enrolamientocredencial_medios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Recurso del sistema',
                'verbose_name_plural': 'Recursos del sistema (catálogo de permisos)',
                'db_table': 'sicre_cat_recurso_sistema',
                'permissions': [('ver_enrolamiento', 'Ver: Enrolamiento'), ('ver_registro_empleado', 'Ver: Registro rápido de empleado'), ('ver_plantilla_anam', 'Ver: Carga manual ANAM'), ('ver_provisional', 'Ver: Carga manual Nuevo Laredo'), ('ver_familiar', 'Ver: Familiares Nuevo Laredo'), ('ver_busqueda_avanzada', 'Ver: Búsqueda avanzada'), ('ver_busqueda_enrolamiento_masivos', 'Ver: Búsqueda de enrolamiento masivo'), ('ver_enrolamiento_masivo', 'Ver: Enrolamiento masivo'), ('ver_carga_masiva', 'Ver: Carga masiva de Excel'), ('ver_credencializacion', 'Ver: Credencialización (legado)'), ('ver_reportes', 'Ver: Reportes'), ('ver_plantillas', 'Ver: Editor de plantillas'), ('ver_imprimir_credenciales', 'Ver: Imprimir credenciales'), ('ver_enrolamiento_previo', 'Ver: Enrolamiento previo'), ('ver_inventario_medios', 'Ver: Inventario de medios'), ('ver_catalogo_areas', 'Ver: Catálogo de áreas'), ('ver_auditoria_credenciales', 'Ver: Auditoría de credenciales'), ('plantillas_administrar', 'Plantillas: crear, editar, eliminar y marcar por defecto'), ('medios_administrar', 'Inventario de medios: reemplazar, renombrar y eliminar'), ('areas_administrar', 'Catálogo de áreas: crear, editar y eliminar'), ('credenciales_editar_ajustes', 'Imprimir credenciales: usar el modo edición rápida')],
                'managed': True,
            },
        ),
    ]
