# Generated by Django 5.1.15 on 2026-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0027_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcuseCredencial',
            fields=[
                ('id_acuse', models.AutoField(primary_key=True, serialize=False)),
                ('num_empleado', models.CharField(db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('alta', 'Acuse de alta'), ('baja', 'Acuse de baja')], max_length=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_carga', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Acuse de credencial',
                'verbose_name_plural': 'Acuses de credencial',
                'db_table': 'sicre_tbl_acuse_credencial',
                'ordering': ['-fecha_carga'],
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='recursosistema',
            options={'managed': True, 'permissions': [('ver_enrolamiento', 'Ver: Enrolamiento'), ('ver_registro_empleado', 'Ver: Registro rápido de empleado'), ('ver_plantilla_anam', 'Ver: Carga manual ANAM'), ('ver_provisional', 'Ver: Carga manual Nuevo Laredo'), ('ver_familiar', 'Ver: Familiares Nuevo Laredo'), ('ver_busqueda_avanzada', 'Ver: Búsqueda avanzada'), ('ver_busqueda_enrolamiento_masivos', 'Ver: Búsqueda de enrolamiento masivo'), ('ver_enrolamiento_masivo', 'Ver: Enrolamiento masivo'), ('ver_carga_masiva', 'Ver: Carga masiva de Excel'), ('ver_credencializacion', 'Ver: Credencialización (legado)'), ('ver_reportes', 'Ver: Reportes'), ('ver_plantillas', 'Ver: Editor de plantillas'), ('ver_imprimir_credenciales', 'Ver: Imprimir credenciales'), ('ver_enrolamiento_previo', 'Ver: Enrolamiento previo'), ('ver_inventario_medios', 'Ver: Inventario de medios'), ('ver_catalogo_areas', 'Ver: Catálogo de áreas'), ('ver_auditoria_credenciales', 'Ver: Auditoría de credenciales'), ('ver_acuses', 'Ver: Acuses de alta/baja'), ('plantillas_administrar', 'Plantillas: crear, editar, eliminar y marcar por defecto'), ('medios_administrar', 'Inventario de medios: reemplazar, renombrar y eliminar'), ('medios_respaldo', 'Administración: descargar respaldo (zip) de fotos y firmas'), ('areas_administrar', 'Catálogo de áreas: crear, editar y eliminar'), ('credenciales_editar_ajustes', 'Imprimir credenciales: usar el modo edición rápida')], 'verbose_name': 'Recurso del sistema', 'verbose_name_plural': 'Recursos del sistema (catálogo de permisos)'},
        ),
    ]
