# Generated by Django 5.1.15 on 2026-08-11 22:56

from django.db import migrations, models


def deduplicar_acuses(apps, schema_editor):
    """
    El modelo pasa de "una fila por carga" a "una fila por (num_empleado,
    tipo)" -- necesario antes de que el paso siguiente agregue la restriccion
    UNIQUE, o MySQL la rechaza si ya hay duplicados (los hubo: se probo el
    endpoint de subida antes de este cambio de diseño).

    Por cada llave duplicada se conserva la fila MAS ANTIGUA (fecha_carga
    real de la primera subida) y las demas se colapsan en
    fecha_modificacion/id_usuario_modifica de esa fila, tomando la mas
    reciente como el ultimo reemplazo -- exactamente el dato que la fila
    sobreviviente habria tenido si el codigo nuevo hubiera estado desde el
    principio.
    """
    AcuseCredencial = apps.get_model('credencializacion', 'AcuseCredencial')
    vistos = {}
    for fila in AcuseCredencial.objects.order_by('fecha_carga'):
        llave = (fila.num_empleado, fila.tipo)
        canonico = vistos.get(llave)
        if canonico is None:
            vistos[llave] = fila
            continue

        canonico.fecha_modificacion = fila.fecha_carga
        canonico.id_usuario_modifica = fila.id_usuario_carga
        canonico.save(update_fields=['fecha_modificacion', 'id_usuario_modifica'])
        fila.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0028_acusecredencial_alter_recursosistema_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='acusecredencial',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acusecredencial',
            name='id_usuario_modifica',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(deduplicar_acuses, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='acusecredencial',
            unique_together={('num_empleado', 'tipo')},
        ),
    ]
