# Generated by Django 5.1.15 on 2026-08-19 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credencializacion', '0029_acusecredencial_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acusecredencial',
            options={'managed': True, 'ordering': ['num_empleado', 'tipo', 'numero'], 'verbose_name': 'Acuse de credencial', 'verbose_name_plural': 'Acuses de credencial'},
        ),
        migrations.AlterUniqueTogether(
            name='acusecredencial',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='acusecredencial',
            name='numero',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='acusecredencial',
            unique_together={('num_empleado', 'tipo', 'numero')},
        ),
    ]
