"""
Django settings for sicre_ws project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-jv6rmkc#@ee793nts78h0_7t(0ygq9yr7(+1@7fwvt7o+tpxkv'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.environ.get('DJANGO_DEBUG', 'True') == 'True' else False

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '168.231.73.222,localhost,127.0.0.1,sicre-anam.ddns.net,siorh-anam.ddns.net').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://sicre-anam.ddns.net,https://168.231.73.222,https://localhost:5555,https://siorh-anam.ddns.net').split(',')

# Asegurarnos de que Django sepa que estamos detrás de un proxy seguro
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'credencializacion',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Comprime las respuestas grandes: el dataset completo del roster SIG
    # (endpoint empleados-sig/todos/, ~16k registros) pesa ~8 MB en crudo y
    # baja a ~1 MB comprimido.
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sicre_ws.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sicre_ws.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        # El MySQL es REMOTO: abrir la conexion cuesta ~1.9 s (medido), contra
        # ~0.3 s que tarda una consulta ya conectado. Con el valor por omision
        # (0) Django cierra la conexion al terminar cada request y la siguiente
        # vuelve a pagar ese costo, asi que hasta un SELECT de una tabla de 2
        # filas tardaba cerca de 2 s. Reutilizarla durante 60 s elimina ese
        # costo en todos los endpoints.
        #
        # 60 s esta muy por debajo del wait_timeout del servidor (28800 s), y
        # CONN_HEALTH_CHECKS hace que Django valide la conexion al reusarla:
        # si el servidor la cerro por su cuenta, reconecta en vez de fallar.
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
    }
}


# DRF: se habilita autenticacion real (antes no habia NINGUN bloque
# REST_FRAMEWORK, asi que todo caia en el default AllowAny sin autenticar a
# nadie -- ver CLAUDE.md, gotcha #3).
#
# `DEFAULT_PERMISSION_CLASSES` se queda en AllowAny A PROPOSITO: cerrar todos
# los endpoints de golpe romperia produccion, hay ~40 vistas que hoy asumen
# que no hace falta sesion. Lo que cambia es que `request.user` ahora SI se
# resuelve cuando llega un token valido, lo que permite: (a) sellar quien
# hizo cada accion en las columnas de auditoria (id_usuario_registra /
# id_usuario_modifica), y (b) exigir `IsAuthenticated` / permisos concretos
# en las vistas NUEVAS (administracion de usuarios y roles) sin tocar las
# demas. Cerrar el resto de los endpoints, uno por uno, queda como trabajo
# aparte y deliberado, no un efecto colateral de este cambio.
#
# BearerTokenAuthentication (no el TokenAuthentication de DRF a secas): el
# frontend ya manda `Authorization: Bearer <token>` (TokenInterceptor), y el
# prefijo que DRF reconoce por omision es `Token`. Se adapta el backend en
# vez de tocar el interceptor, que corre en cada peticion del sistema.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'credencializacion.auth.BearerTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Archivos de medios (fotos, firmas y fondos de plantillas de credencial)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Subcarpetas dentro de MEDIA_ROOT. Las fotos y firmas historicas ya viven aqui
# nombradas por num_empleado (ver EnrolamientoCredencial.resolver_archivo_existente).
MEDIA_DIR_FOTOS = 'fotos'
MEDIA_DIR_FIRMAS = 'FIRMAS'
MEDIA_DIR_PLANTILLAS = 'plantillas'
MEDIA_DIR_ACUSE_ALTA = 'acuse_alta'
MEDIA_DIR_ACUSE_BAJA = 'acuse_baja'

# Los fondos de plantilla (subir-fondo, PlantillaCredencialViewSet) viajan
# como base64 dentro del cuerpo JSON, no como multipart -- eso los infla
# ~33% y los hace pasar por el limite de Django para el body completo
# (DATA_UPLOAD_MAX_MEMORY_SIZE), no por FILE_UPLOAD_MAX_MEMORY_SIZE. El
# default de Django es 2.5 MB: una foto de prueba chica pasa sin problema,
# pero un fondo de credencial real (arte a resolucion de impresion) lo
# rebasa seguido -- de ahi las fallas intermitentes solo en produccion con
# imagenes de verdad, nunca en pruebas locales con archivos pequeños. Se
# suben ambos limites para dejar margen: 20 MB de archivo crudo ya cubre
# holgadamente el ~33% de inflado del base64.
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024

# Configuración CORS
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.environ.get(
        'CORS_ALLOWED_ORIGINS',
        'http://168.231.73.222,https://168.231.73.222,http://localhost:5555'
    ).split(',')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

